# Generated by Django 5.1.6 on 2025-02-20 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookmodel_options_alter_bookmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevieweModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_text', models.TextField(default='Рекомендую')),
                ('stars', models.CharField(choices=[('⭐️', '⭐️'), ('⭐️⭐️', '⭐️⭐️'), ('⭐️⭐️⭐️', '⭐️⭐️⭐️'), ('⭐️⭐️⭐️⭐️', '⭐️⭐️⭐️⭐️'), ('⭐️⭐️⭐️⭐️⭐️', '⭐️⭐️⭐️⭐️⭐️')], default='⭐️⭐️⭐️⭐️⭐️', max_length=20)),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_books', to='books.bookmodel')),
            ],
        ),
    ]
