# Generated by Django 5.1.6 on 2025-02-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_reviewemodel_user_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RevieweModel',
            new_name='ReviewModel',
        ),
    ]
