# Generated by Django 5.1.6 on 2025-02-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0005_rename_reviewemodel_reviewmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Введите ваш точный адрес для доставки: ')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Введите номер телефона: ')),
                ('payment', models.CharField(choices=[('Наличные', 'Наличные'), ('Перевод', 'Перевод')], max_length=15, verbose_name='Укажите способ оплаты: ')),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookmodel', verbose_name='Добавьте книгу в заказ')),
            ],
        ),
    ]
