# Generated by Django 5.1.6 on 2025-02-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_reviewemodel_reviewmodel'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartModel',
        ),
    ]
